[package]
name = "protocols"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "protocols"
path = "src/lib.rs"

[dependencies]
heapless = { version = "0.8", features = ["serde"] }
sha1 = { version = "0.10", default-features = false }
binascii = { version = "0.1.4", default-features = false, features = ["encode"] }
modular-bitfield = { version = "0.13.0" }

[features]
default = []
std = []

# Specifies that this is a no_std library by default
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
